### ISSUE TITLE
Чистка исходников клиента

### ISSUE THREAD

**Issue by SGmuwa** [gosharas/untitled#12]
Требуется, чтобы в клиенте не присутствовали `.java` файлы, которые не используются.

**Comment by SGmuwa** [comment]
Couple.java может тоже убрать?

**Comment by gosharas** [comment]
InputSeeker как раз использует все это

**Comment by SGmuwa** [comment]
@gosharas, ссылка [Couple.java](https://github.com/gosharas/untitled/blob/develop/client-exel/src/main/java/ru/gosha/Couple.java) из [InputSeeker.java](https://github.com/gosharas/untitled/blob/develop/client-exel/src/main/java/ru/gosha/InputSeeker.java) не найдена, поэтому я предлагаю удалить Couple.java

**Comment by gosharas** [comment]
@SGmuwa InpurSeeker использует Seeker, последний же использует SeekerType и Couple

**Comment by SGmuwa** [comment]
@gosharas, исправлено в 6ca68187d4d915fa0e14fb90e881ca0c5d8eaa13

**Comment by SGmuwa** [comment]
Буду сейчас [доделовать ](https://quire.io/w/4vr/57#comment-PMSioJnvgOz1aK2XYzoaKJ..) задачу #15 чтобы можно было продолжать разработку клиента полным ходом.

**Comment by SGmuwa** [comment]
Клиент полностью чист к https://github.com/gosharas/untitled/commit/3f172a0a8594b1251d014141bd895a1ef6741bf8
